name: pitstrainintgpart1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_provider:
  http:
  dartz:
  equatable:
  get_it:
  internet_connection_checker:
  shared_preferences:
  cached_network_image:
  flutter_svg: ^2.0.7

  
#  Responsive
  flutter_screenutil: ^5.9.3

# charts
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
